# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_type', models.IntegerField()),
                ('is_fid', models.IntegerField()),
                ('course_name', models.CharField(max_length=200)),
                ('course_big_user', models.IntegerField()),
                ('course_score', models.IntegerField()),
                ('course_begin_time', models.CharField(max_length=200)),
                ('course_end_time', models.CharField(max_length=200)),
                ('course_time', models.CharField(max_length=200)),
                ('course_content', models.TextField(blank=True)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.Building')),
            ],
        ),
        migrations.CreateModel(
            name='SignUpList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.CourseInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_pass', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('user_type', models.IntegerField()),
                ('photo', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('sex', models.CharField(blank=True, max_length=200)),
                ('content', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='signuplist',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.UserInfo'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.Rooms'),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teaching.UserInfo'),
        ),
    ]
